import type { Metadata } from 'next'
import { ChakraUIProvider } from '../provider/ChakraUIProvider'
import './globals.css'
import Layout from '@/component/layout/Layout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraUIProvider>
          <Layout>{children}</Layout>
        </ChakraUIProvider>
      </body>
    </html>
  )
}
