name: mincho-log

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: run build
        run: |
          yarn install
          yarn tsc
          yarn build
        continue-on-error: true
      - uses: actions/github-script@v6
        if: failure()
        with:
          github-token: ${{secrets.TOKEN_FOR_CI}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '빌드에 실패했습니다. 로그를 확인해주세요.'
            })
